### ISSUE TITLE
Design content for the 404 page

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/gfsc-v3#293]
## Description

This is our 404 page

![0d33e158 gfsc pages dev_bork](https://github.com/geeksforsocialchange/gfsc-v3/assets/46496391/3ed45039-a4b9-48f1-8995-747f92fa1e70)

It would be nice to add some useful or entertaining info here. @aaaaargZombies made this suggestion

![image](https://github.com/geeksforsocialchange/gfsc-v3/assets/46496391/07024c1d-1fb2-427b-aa2a-cfccdcd8a865)

@undividual's input: 

> The only thing I'd change is make 'How did I get here' read 'Error 404: page not found' — as then the venn diagram works as a venn diagram

We just wanted to know if anyone else from the content team @honor-gfsc @rebeccawigmore had any opinions on this before we go ahead with it!

**Comment by honor-gfsc** [comment]
i enjoy this! and agree with @undividual 's edit

**Comment by rebeccawigmore** [comment]
I enjoy this and I have a couple suggestions! Comedy rule of three is calling out to me here, so I suggest we augment the Pie-chart reasons so they appear in this order. I've also corrected overzealous as it turns out it is one word, like autocorrect!


Top left: OVERZEALOUS AUTOCORRECT
Top right: POCKET BROWSING
Bottom: CURSED BY WITCH ON BIRTHDAY

Also, the joke needs to have the "how did I get here?" question, otherwise it requires too much inference to land immediately. But Error 404 is important! So I suggest:

Header: Error 404
Centre of pie: How did I get here?

**Comment by r-ferrier** [comment]
I am assuming @honor-gfsc meant this comment made in discord:

<img width="702" alt="Screenshot 2023-08-21 at 09 45 07" src="https://github.com/geeksforsocialchange/gfsc-v3/assets/46496391/7ad63f38-daa1-458c-b968-58da2f890cbf">

**Comment by honor-gfsc** [comment]
yep, as you copied above!
