### ISSUE TITLE
[Bug]: filter switcher on `our work` rendered inoperable if JS doesn't load or is disabled

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/gfsc-v3#328]
## Description

filter switcher on `our work` rendered inoperable if JS doesn't load or is disabled, consider rendering in open state statically then hiding once JS runs so it is ugly but functional as fallback.

## Steps to reproduce

1. What you did first
1. What you did next

## Platform (if relevant)

What device and browser were you using?

**Comment by kimadactyl** [comment]
do we care? im not sure what modern logic is on if people having js disabled is a real thing we need to care about

**Comment by katjam** [comment]
It is still considered good practice to provide a graceful alternative
state for js driven content. Particularly if the site is otherwise static
content.

**Comment by kimadactyl** [comment]
considered by who? not trying to be difficult i just want to know more about motivation. noone is asking sites to work without CSS, for example

**Comment by katjam** [comment]
It may be something we don't want to support but it should be a deliberate
decision we make. People do also access sites as plain text (no CSS). I'll
dig put some references.

**Comment by r-ferrier** [comment]
I *think* we can do this with css (https://stackoverflow.com/questions/6019845/show-hide-div-on-click-with-css
) so I'm going to investigate but will not spend a huge amount of time on this. 

Although I can definitely see the argument for a largely static site running nicely without js, I think I'm with Kim on this issue and I'm especially against defaulting to all options on this page because once the js loads a split second later it will change the appearance, which will be really jarring for 99% of our visitors. 

Also although you can't search by project type on this page if it doesn't load, you can still view every project, which feels like a decent enough fallback to me?

**Comment by r-ferrier** [comment]
Css: just because we can, in this instance, I do not think we should! Too many accessibility inconsistencies would be introduced.

We've decided to not fix this in this sprint using js because the only simple option would introduce a page jump on load.
